- hosts: k8s
  name: node init
  tasks:
    - name: add chmod
      command: chmod a+x /usr/local/bin/init.sh
    - name: start init
      command: /usr/local/bin/init.sh
      register: cmd_result
    - name: Show init result
      debug:
        msg: "{{cmd_result.stdout_lines}}"  # 使用debug模块显示输出

